version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ml_ops
    ports:
      - '5432:5432'
    networks:
      - internal
    volumes:
      - db:/var/lib/postgresql/data